# Generated by Django 4.2.1 on 2023-05-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("Product_name", models.CharField(max_length=50)),
                ("category", models.CharField(default="", max_length=50)),
                ("sub_category", models.CharField(default="", max_length=50)),
                ("price", models.IntegerField()),
                ("desc", models.CharField(max_length=300)),
                ("image", models.ImageField(upload_to="image/images")),
            ],
        ),
    ]
